<?xml version = "1.0"?>  
<!DOCTYPE document [  
<!ELEMENT document (employee)*>  
<!ELEMENT employee (empid, empname, salary, dob, doj, address, deptname, designation)>  
<!ELEMENT empid (#PCDATA)>  
<!ELEMENT empname (fname, lname)>  
<!ELEMENT fname (#PCDATA)>  
<!ELEMENT lname (#PCDATA)>  
<!ELEMENT salary (#PCDATA)>  
<!ELEMENT dob (#PCDATA)>  
<!ELEMENT doj (#PCDATA)>  
<!ELEMENT address (#PCDATA)>  
<!ELEMENT deptname (#PCDATA)>  
<!ELEMENT designation (#PCDATA)>  
] > 

<?xml-stylesheet type="text/xsl" href="index.xsl"?>  
<document> 
    <employee> 
        <empid>1</empid> 
        <empname> 
            <fname>Chris</fname> 
            <lname>Parker</lname> 
        </empname> 
        <salary>20000</salary> 
        <dob>20/03/1984</dob> 
        <doj>25/04/2007</doj> 
        <address>USA</address> 
        <deptname>HR</deptname> 
        <designation>Manager</designation> 
    </employee> 

    <employee> 
        <empid>2</empid> 
        <empname> 
            <fname>Riya</fname> 
            <lname>Parker</lname> 
        </empname> 
        <salary>25000</salary> 
        <dob>11/08/1986</dob> 
        <doj>13/04/2008</doj> 
        <address>USA</address> 
        <deptname>Sales</deptname> 
        <designation>Clerk</designation> 
    </employee> 

    <employee> 
        <empid>3</empid> 
        <empname> 
            <fname>Emma</fname> 
            <lname>Parker</lname> 
        </empname> 
        <salary>22000</salary> 
        <dob>14/12/1985</dob> 
        <doj>09/05/2009</doj> 
        <address>USA</address> 
        <deptname>Marketing</deptname> 
        <designation>Asst. Manager</designation> 
        </employee> 
        
    <employee> 
        <empid>4</empid> 
        <empname> 
            <fname>Paul</fname> 
            <lname>Parker</lname> 
        </empname> 
        <salary>35000</salary> 
        <dob>17/11/1980</dob> 
        <doj>18/09/2004</doj> 
        <address>UK</address> 
        <deptname>Sales</deptname> 
        <designation>Manager</designation> 
    </employee> 

    <employee> 
        <empid>5</empid> 
        <empname> 
            <fname>Elle</fname> 
            <lname>Parker</lname> 
        </empname> 
        <salary>32000</salary> 
        <dob>11/06/1982</dob> 
        <doj>11/01/2005</doj> 
        <address>USA</address> 
        <deptname>Finance</deptname> 
        <designation>Manager</designation> 
    </employee> 
</document> 
